version: "3.8"

services:
    app:
        container_name: archub-v2-app
        image: archub-v2-app:latest
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        container_name: archub-v2-db
        platform: "linux/amd64"
        image: mysql:5.7
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

    nginx:
        image: nginx:alpine
        container_name: archub-v2-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d

volumes:
    dbdata:
